---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    
install:
  # Install ansible
  - pip install ansible ansible-lint yamllint openstacksdk python-magnumclient python-heatclient python-novaclient

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Compensate for repo name being different to the role
  - ln -s $(pwd) ../stackhpc.os-container-infra

  # Obtain custom yamllint rules for Ansible
  - curl -O https://raw.githubusercontent.com/ansible/galaxy/devel/galaxy/importer/linters/yamllint.yaml


script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Ansible lint
  - ansible-lint tests/test.yml
  # YAML lint
  - yamllint -c yamllint.yaml .

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
