---

- name: Get container infra details
  os_container_infra:
    cloud_name: "{{ os_container_infra_config_cloud_name }}"
    create_if_not_found: "{{ os_container_infra_config_create_if_not_found }}"
    cluster_name: "{{ os_container_infra_config_cluster_name }}"
    cluster_template_name: "{{ os_container_infra_config_cluster_template_name }}"
    master_count: "{{ os_container_infra_config_master_count }}"
    node_count: "{{ os_container_infra_config_node_count }}"
    keypair: "{{ os_container_infra_config_keypair }}"
  register: results
  become: no
- debug: msg="{{ results['container_infra'] | from_json }}"
