---
- name: Get container infra details
  os_container_infra:
    cloud: "{{ os_container_infra_cloud }}"
    state: "{{ os_container_infra_state }}"
    cluster_name: "{{ os_container_infra_cluster_name }}"
    cluster_template_name: "{{ os_container_infra_cluster_template_name }}"
    master_count: "{{ os_container_infra_master_count }}"
    node_count: "{{ os_container_infra_node_count }}"
    keypair: "{{ os_container_infra_keypair }}"

- block:
  - name: Get stack facts
    os_stack_facts:
      cloud: "{{ os_container_infra_cloud }}"
      stack_id: "{{ container_infra.stack_id }}"
      nested_depth: 4
      filters:
        resource_type: 'OS::Nova::Server'

  - name: Attach interfaces to servers
    os_server_interface:
      cloud: "{{ os_container_infra_cloud }}"
      server_id: "{{ item['physical_resource_id'] }}"
      interfaces: "{{ os_container_infra_interfaces }}"
      state: present
    register: server_interface_facts
    with_items: "{{ stack_facts }}"

  - name: Ensure container infra inventory directory exists
    file:
      path: "{{ os_container_infra_inventory | dirname }}"
      state: directory
    when: os_container_infra_inventory is defined

  - name: Generate cluster inventory
    template:
      src: inventory-container-infra.j2
      dest: "{{ os_container_infra_inventory }}"
  when: os_container_infra_state == 'present'
...
