---
- name: os_container_infra_state != 'upgrade'
  include_tasks: not-upgrade.yml
  when:
    - os_container_infra_state != 'upgrade'

- name: os_container_infra_state == 'upgrade'
  vars:
    k8s_version: "{{ os_container_infra_k8s_version }}"
  include_tasks: upgrade.yml
  when:
    - os_container_infra_state == 'upgrade'
    - os_container_infra_coe == 'kubernetes'
    - os_container_infra_k8s_version is defined
  loop: "{{ os_container_infra_k8s_services }}"
  loop_control:
    loop_var: k8s_service
...
