---
- block:
    - name: "Obtain cluster template ID for cluster named {{ os_container_infra_template_name }}"
      os_coe_cluster_template:
        auth_type: "{{ os_container_infra_auth_type or omit }}"
        auth: "{{ os_container_infra_auth or omit }}"
        cloud: "{{ os_container_infra_cloud or omit }}"
        name: "{{ os_container_infra_template_name }}"
        coe: "{{ os_container_infra_coe }}"
        image_id: "{{ os_container_infra_image }}"
      register: cluster_template
    - name: Extract the cluster ID
      set_fact:
        os_container_infra_template_id: "{{ cluster_template.id }}"
  when:
    - not os_container_infra_template_id
    - os_container_infra_state == 'present'

- name: "Ensure container cluster is {{ os_container_infra_state }}"
  os_coe_cluster:
    auth_type: "{{ os_container_infra_auth_type or omit }}"
    auth: "{{ os_container_infra_auth or omit }}"
    cloud: "{{ os_container_infra_cloud or omit }}"
    state: "{{ os_container_infra_state }}"
    name: "{{ os_container_infra_name }}"
    cluster_template_id: "{{ os_container_infra_template_id or omit }}"
    master_count: "{{ os_container_infra_master_group.count | int }}"
    node_count: "{{ os_container_infra_worker_group.count | int }}"
    keypair: "{{ os_container_infra_keypair }}"
    labels: "{{ os_container_infra_labels or omit }}"
    wait: True
  register: container_infra

- import_tasks: present.yml
  when: os_container_infra_state == 'present'
