---

- name: Get magnum access info
  os_container_infra:
    cloud_name: "{{ os_container_infra_config.cloud_name }}"
    magnum_endpoint: "{{ os_container_infra_config.magnum_endpoint }}"
    cluster_name: "{{ os_container_infra_config.cluster_name }}"
    cluster_template_name: "{{ os_container_infra_config.cluster_template_name }}"
    master_count: "{{ os_container_infra_config.master_count }}"
    node_count: "{{ os_container_infra_config.node_count }}"
    keypair: "{{ os_container_infra_config.keypair }}"
  register: os_container_infra_result
  become: no

- debug: var=os_container_infra_result

- fail:
